sudo: false
language: generic
branches:
    only:
        - cv
addons:
    apt:
        packages:
            - texlive-latex-base
            - texlive-latex-recommended
            - texlive-latex-extra
            - texlive-generic-recommended
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - texlive-publishers
before_script:
    - pip install ads
script:
    - ./update_cv.sh

after_success:
    - ./deploy.sh
