sudo: false
language: generic
branches:
    only:
        - cv
addons:
    apt:
        packages:
            - texlive-latex-base
            - texlive-latex-recommended
            - texlive-latex-extra
            - texlive-generic-recommended
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - texlive-publishers
before_script:
    - pip install ads
script:
    - ./update_cv.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: pdf/
  target_branch: master
